# Generated by Django 3.2.14 on 2024-05-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman')], max_length=20),
        ),
    ]
