# Generated by Django 3.2.14 on 2024-05-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularuser',
            name='approval_document',
            field=models.FileField(null=True, upload_to='approval_documents/'),
        ),
        migrations.AddField(
            model_name='regularuser',
            name='img',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='regularuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
