# Generated by Django 3.2.14 on 2024-05-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='preview',
            field=models.ImageField(null=True, upload_to='preview/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(null=True, upload_to='business/'),
        ),
    ]
